# fly.toml app configuration file generated for teamup on 2024-08-12T18:24:28+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teamup'
primary_region = 'sin'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_NAME = "TeamUp"
  APP_ENV = 'production'
  APP_DEBUG=true
  APP_TIMEZONE = "Asia/Singapore"
  APP_URL = "https://teamup.fly.dev"
  ASSET_URL="https://teamup.fly.dev"


  APP_LOCALE = "en"
  APP_FALLBACK_LOCALE = "en"
  APP_FAKER_LOCALE = "en_US"

  APP_MAINTENANCE_DRIVER = "file"
  CACHE_DRIVER = "file"

  BCRYPT_ROUNDS = 12

  LOG_CHANNEL="stack"
  LOG_STACK="single"
  LOG_DEPRECATIONS_CHANNEL="null"
  LOG_LEVEL="debug"

  GITHUB_REDIRECT_URL="/login/github/callback"
  GOOGLE_REDIRECT_URL="/login/google/callback"

  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  
  DB_CONNECTION='pgsql'
  DB_HOST='aws-0-ap-southeast-1.pooler.supabase.com'
  DB_PORT='6543'
  DB_DATABASE='postgres'

  BROADCAST_CONNECTION="log"
  FILESYSTEM_DISK="local"
  QUEUE_CONNECTION="database"

  MAIL_MAILER="smtp"
  MAIL_HOST="smtp.gmail.com"
  MAIL_PORT=465
  MAIL_USERNAME="teamup.4dmin@gmail.com"
  MAIL_ENCRYPTION="tls"
  MAIL_FROM_ADDRESS="teamup.4dmin@gmail.com"
  MAIL_FROM_NAME="TeamUp"
  

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="storage_dir"
  destination="var/www/html/storage"
  
[deploy]
release_command = "/populate_volume.sh"


[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
