# fly.toml app configuration file generated for teamup on 2024-08-12T18:24:28+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teamup'
primary_region = 'sin'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  DB_CONNECTION='pgsql'
  DB_HOST='aws-0-ap-southeast-1.pooler.supabase.com'
  DB_PORT='6543'
  DB_DATABASE='postgres'
  DB_SSL_MODE='require'
  

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="storage_dir"
  destination="var/www/html/storage"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
